name: Build Custom

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
#                    ZETTLR MAIN BUILD GITHUB ACTIONS FILE                    #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
#      !!! Modified by @kyaso to only build Linux AppImages !!!               #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# This file contains the logic necessary to build a full release from source. #
#                                                                             #
# WHEN IT RUNS:                                                               #
#                                                                             #
# * Whenever someone successfully pushes develop --> master.                  #
# * Every Monday at noon (UTC)                                                #
# * Manually                                                                  #
#                                                                             #
# The last two events are being used to create nightly releases. The first    #
# event type indicates that the pipeline should build a regular release.      #
#                                                                             #
# HOW IT RUNS:                                                                #
#                                                                             #
# 1. Three virtual machines are spun up in parallel: A Windows VM, a Ubuntu   #
#    VM, and a macOS VM. All three are tasked with building all releases that #
#    we offer for the given platform. The Ubuntu VM builds the most since we  #
#    have many more Linux releases. Windows and macOS only build one x64 and  #
#    one ARM release. However, they also perform code signing (and            #
#    notarization in case of the macOS VM), which the Ubuntu VM doesn't do.   #
# 2. Each VM uploads all resulting artifacts into their respective artifact   #
#    space, named "linux", "darwin", and "win32" respectively (analogous to   #
#    node.js's process.platform-variable).                                    #
# 3. Iff (if and only if) all three runners have shut down successfully,      #
#    indicating successful builds, another Ubuntu VM will be started. That    #
#    one is tasked with downloading all releases from the three artifact      #
#    spaces, calculate the SHA-256 checksums for every file and afterwards    #
#    upload all files: In case of a nightly to the Zettlr server, where they  #
#    can be downloaded from nightly.zettlr.com, or, in case of a regular      #
#    release, to a newly created release draft here on GitHub.                #
#                                                                             #
# THINGS TO NOTE:                                                             #
#                                                                             #
# * Every runner will retrieve the package.json's "version" field by running  #
#   a somewhat weird-looking command. This is necessary to make finding the   #
#   releases easier which are being produced by electron-forge and electron-  #
#   builder.                                                                  #
# * Especially the macOS runner can often produce problems, because there     #
#   have been rumors that apparently even the macOS server operating systems  #
#   tend to open modal windows -- even though they're running headless. This  #
#   means that in case the macOS runners seem to hang it's likely we again    #
#   need to update the add-osx-cert.sh script.                                #
# * Everything is being run on Bash. Although PowerShell can do a lot, this   #
#   way all steps are within one language, making it easier to maintain.      #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

on:
  push:
    branches:
      - custom
  workflow_dispatch: # Used to manually trigger a nightly build.
    inputs:
      target:
        # Access using github.event.inputs.target
        description: 'Target ("nightly"/"stable")'     
        required: false
        default: 'stable'

# Defaults for every job and step in this workflow
defaults:
  run:
    shell: bash # Run everything using bash

# Global environment variables
env:
  # Easy way to set the node version
  NODE_VERSION: '16'
  # Whenever we either trigger a build manually *or* a scheduled run starts,
  # this indicates a nightly build, and NOT a regular, stable release. We are
  # writing it here into the environment variable to keep the code DRY and for
  # easier reference.
  # BUG: Disabled due to a bug in Github Actions that will not resolve this
  # environment variable, thus rendering this approach unusable. We have to
  # manually copy this into the appropriate places.
  # BUILD_NIGHTLY: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
  BRANCH: 'custom'

# This workflow file contains four jobs, three to build the corresponding
# releases on all three supported platforms, and a last one, which will
# create the release draft.
jobs:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                               LINUX BUILDS                                #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  build_linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo (custom branch)
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: yarn install --frozen-lockfile
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
          tag=$(git describe --tags --abbrev=0)
          echo ::set-output name=latestTag::$tag
      - name: No new version detected
        if: ${{ format('v{0}', steps.ref.outputs.version) == steps.ref.outputs.latestTag }}
        run: |
          echo "::error file=package.json::Did you forget to update the version in package.json?"
          exit 1
      - name: Package Linux targets (x64)
        run: yarn package:linux-x64
      - name: Create Linux installers (x64)
        run: yarn release:linux-x64
      - name: Rename executable
        run: mv ./release/Zettlr* ./release/Zettlr-${{steps.ref.outputs.version}}-x86_64.AppImage
      # After everything has been created, now we need to cache them.
      - name: Cache installers
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            ./release/Zettlr-${{steps.ref.outputs.version}}-x86_64.AppImage
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                               WINDOWS BUILDS                              #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  build_win:
    name: Windows build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo (custom branch)
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: yarn install --frozen-lockfile
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
          tag=$(git describe --tags --abbrev=0)
          echo ::set-output name=latestTag::$tag
      - name: No new version detected
        if: ${{ format('v{0}', steps.ref.outputs.version) == steps.ref.outputs.latestTag }}
        run: |
          echo "::error file=package.json::Did you forget to update the version in package.json?"
          exit 1
      - name: Package Windows targets (x64)
        run: yarn package:win-x64
      - name: Build NSIS installer (x64)
        run: yarn release:win-x64
      #- name: Rename executable
      #  run: mv ./release/Zettlr* ./release/Zettlr-${{steps.ref.outputs.version}}-x86_64.AppImage
      # After everything has been created, now we need to cache them.
      - name: Cache installers
        uses: actions/upload-artifact@v2
        with:
          name: win32
          path: |
            ./release/Zettlr-${{steps.ref.outputs.version}}-x64.exe

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                                                                           #
  #                          PREPARE RELEASE DRAFT                            #
  #                                                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # After the three builds, this job downloads all assets, creates and verifies
  # SHA256 checksums, and finally creates a release draft and uploads all
  # assets to it. NOTE: If the workflow detects a nightly is being built, this
  # step rather uploads the binaries to the Zettlr server instead of creating
  # a release draft.
  prepare_release:
    name: Prepare release draft
    # Make sure (and wait until) the builds have succeeded
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up build environment
        run: yarn install --frozen-lockfile
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      - name: Add Git tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{steps.ref.outputs.version}}
      - name: Make release directory
        run: mkdir ./release
      # First, download all resulting assets from the previous steps.
      - name: Retrieve Linux installers
        uses: actions/download-artifact@v2
        with:
          name: linux
          path: ./release
      - name: Retrieve windows installers
        uses: actions/download-artifact@v2
        with:
          name: win32
          path: ./release
      # Now we are set, we have all release assets on the VM. It's time to
      # create the SHA-checksums file and then upload everything!
      - name: Generate SHA256 checksums
        run: |
          cd ./release
          sha256sum "Zettlr-${{steps.ref.outputs.version}}-x86_64.AppImage" > "SHA256SUMS.txt"
          sha256sum "Zettlr-${{steps.ref.outputs.version}}-x64.exe" >> "SHA256SUMS.txt"
          cd ..
      - name: Verify checksums
        run: |
          cd ./release
          sha256sum -c SHA256SUMS.txt
          cd ..
      # Create a new release draft
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Populate the inputs of the release we already know
          tag_name: v${{steps.ref.outputs.version}}
          name: v${{steps.ref.outputs.version}}
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          draft: true # Always create as draft, so that we can populate the remaining values easily
          # Gosh, is that convenient as opposed to earlier!
          files: |
            ./release/Zettlr-${{steps.ref.outputs.version}}-x86_64.AppImage
            ./release/Zettlr-${{steps.ref.outputs.version}}-x64.exe
            ./release/SHA256SUMS.txt
