name: Unit Tests / Lint

on: [push, pull_request]

permissions:
  contents: read

env:
  NODE_VERSION: '16'

jobs:
  check:
    name: Unit Tests / Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Always fetch the branch that triggered the event (develop or master)
        ref: ${{ github.ref }}
    - name: Setup NodeJS ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - name: Install packages
      run: yarn install --immutable
    - name: Run ESLint
      run: yarn lint
    - name: Run unit tests
      run: yarn test
    - name: Test CSL update
      run: yarn update:csl
    - name: Test Citation update
      run: yarn update:citation
